#pragma once

#include <string>
#include <vector>
#include <memory>
#include <optional>

namespace web_page_manager {
namespace ai {

/// Processing mode for AI content analysis
enum class ProcessingMode {
    Basic,    ///< Fast text-only processing
    Enhanced, ///< Full content analysis with media
    Auto      ///< Automatically choose based on content and resources
};

/// Content type classification
enum class ContentType {
    Article,
    Video,
    Documentation,
    SocialMedia,
    Shopping,
    News,
    Reference,
    Other
};

/// Page content structure
struct PageContent {
    std::string html;
    std::string text;
    std::string title;
    std::optional<std::string> description;
    std::vector<std::string> keywords;
    std::vector<std::string> images;
    std::vector<std::string> links;
};

/// Content summary generated by AI
struct ContentSummary {
    std::string summary_text;
    std::vector<std::string> key_points;
    ContentType content_type;
    std::string language;
    uint32_t reading_time_minutes;
    float confidence_score;
};

/// Category information
struct CategoryInfo {
    std::string primary_category;
    std::vector<std::string> secondary_categories;
    float confidence;
};

/// Group suggestion
struct GroupSuggestion {
    std::string group_name;
    std::string description;
    std::vector<std::string> page_ids;
    float similarity_score;
};

/// Relevance score between content
struct RelevanceScore {
    float score;
    std::vector<std::string> common_topics;
    std::vector<std::string> common_keywords;
};

/// Content analysis result
struct ContentAnalysis {
    ContentSummary summary;
    CategoryInfo category;
    std::vector<std::string> entities;
    std::vector<std::string> topics;
    std::string sentiment;
};

/// Topic information
struct TopicInfo {
    std::string main_topic;
    std::vector<std::string> sub_topics;
    float confidence;
};

/// Processing capabilities
struct ProcessingCapabilities {
    bool supports_enhanced_mode;
    bool supports_media_analysis;
    bool supports_sentiment_analysis;
    size_t max_content_length;
    std::vector<std::string> supported_languages;
};

/// Internal processor interface (not exposed to clients)
class IContentProcessor {
public:
    virtual ~IContentProcessor() = default;
    
    virtual ContentSummary GenerateSummary(const PageContent& content) = 0;
    virtual std::vector<std::string> ExtractKeywords(const PageContent& content) = 0;
    virtual CategoryInfo ClassifyContent(const PageContent& content) = 0;
    virtual double CalculateSimilarity(const ContentSummary& a, const ContentSummary& b) = 0;
};

/// Unified AI content processor interface
class AIContentProcessor {
public:
    AIContentProcessor();
    ~AIContentProcessor();
    
    // Prevent copying
    AIContentProcessor(const AIContentProcessor&) = delete;
    AIContentProcessor& operator=(const AIContentProcessor&) = delete;
    
    // Allow moving
    AIContentProcessor(AIContentProcessor&&) noexcept;
    AIContentProcessor& operator=(AIContentProcessor&&) noexcept;
    
    /// Core content analysis capabilities
    ContentSummary GenerateSummary(const PageContent& content);
    std::vector<std::string> ExtractKeywords(const PageContent& content);
    CategoryInfo ClassifyContent(const PageContent& content);
    
    /// Content similarity and grouping
    double CalculateSimilarity(const ContentSummary& a, const ContentSummary& b);
    std::vector<GroupSuggestion> SuggestGroups(const std::vector<PageContent>& pages);
    RelevanceScore CalculateContentRelevance(const PageContent& a, const PageContent& b);
    
    /// Advanced analysis (automatically uses enhanced mode if available)
    ContentAnalysis AnalyzePageStructure(const PageContent& content);
    std::vector<std::string> ExtractPageMetadata(const PageContent& content);
    TopicInfo IdentifyMainTopics(const PageContent& content);
    
    /// Configuration and optimization
    void SetProcessingMode(ProcessingMode mode);
    ProcessingMode GetProcessingMode() const;
    ProcessingCapabilities GetCurrentCapabilities() const;
    
private:
    class Impl;
    std::unique_ptr<Impl> impl_;
};

} // namespace ai
} // namespace web_page_manager
