import 'package:flutter/material.dart';

import '../models/smart_group.dart';

/// Card widget for displaying smart group information
class GroupCard extends StatelessWidget {
  final SmartGroup group;
  final VoidCallback? onTap;

  const GroupCard({
    super.key,
    required this.group,
    this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(12),
        child: Container(
          width: 200,
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(
                    _getGroupIcon(),
                    color: _getGroupColor(),
                    size: 20,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      group.name,
                      style: Theme.of(context).textTheme.titleMedium,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Text(
                group.description,
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: Theme.of(context).colorScheme.outline,
                    ),
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
              ),
              const SizedBox(height: 8),
              Row(
                children: [
                  Icon(
                    Icons.web,
                    size: 14,
                    color: Theme.of(context).colorScheme.outline,
                  ),
                  const SizedBox(width: 4),
                  Text(
                    '${group.pageCount} 个页面',
                    style: Theme.of(context).textTheme.labelSmall?.copyWith(
                          color: Theme.of(context).colorScheme.outline,
                        ),
                  ),
                  if (group.autoGenerated) ...[
                    const Spacer(),
                    Icon(
                      Icons.auto_awesome,
                      size: 14,
                      color: Theme.of(context).colorScheme.primary,
                    ),
                  ],
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  IconData _getGroupIcon() {
    switch (group.groupType) {
      case GroupType.domain:
        return Icons.language;
      case GroupType.topic:
        return Icons.topic;
      case GroupType.contentType:
        return Icons.category;
      case GroupType.userDefined:
        return Icons.folder;
      case GroupType.aiGenerated:
        return Icons.auto_awesome;
    }
  }

  Color _getGroupColor() {
    switch (group.groupType) {
      case GroupType.domain:
        return Colors.blue;
      case GroupType.topic:
        return Colors.green;
      case GroupType.contentType:
        return Colors.orange;
      case GroupType.userDefined:
        return Colors.purple;
      case GroupType.aiGenerated:
        return Colors.teal;
    }
  }
}
