/// Browser types supported by the system
enum BrowserType {
  chrome,
  firefox,
  edge,
  safari,
}

/// Content type classification
enum ContentType {
  article,
  video,
  documentation,
  socialMedia,
  shopping,
  news,
  reference,
  other,
}

/// Page source type
enum PageSourceType {
  activeTab,
  bookmark,
  closedTab,
  archivedContent,
}

/// Content summary generated by AI
class ContentSummary {
  final String summaryText;
  final List<String> keyPoints;
  final ContentType contentType;
  final String language;
  final int readingTimeMinutes;
  final double confidenceScore;
  final DateTime generatedAt;

  ContentSummary({
    required this.summaryText,
    required this.keyPoints,
    required this.contentType,
    required this.language,
    required this.readingTimeMinutes,
    required this.confidenceScore,
    required this.generatedAt,
  });

  factory ContentSummary.fromJson(Map<String, dynamic> json) {
    return ContentSummary(
      summaryText: json['summary_text'] ?? '',
      keyPoints: List<String>.from(json['key_points'] ?? []),
      contentType: _parseContentType(json['content_type']),
      language: json['language'] ?? 'en',
      readingTimeMinutes: json['reading_time_minutes'] ?? 0,
      confidenceScore: (json['confidence_score'] ?? 0.0).toDouble(),
      generatedAt:
          DateTime.tryParse(json['generated_at'] ?? '') ?? DateTime.now(),
    );
  }

  static ContentType _parseContentType(dynamic value) {
    if (value is String) {
      switch (value.toLowerCase()) {
        case 'article':
          return ContentType.article;
        case 'video':
          return ContentType.video;
        case 'documentation':
          return ContentType.documentation;
        case 'socialmedia':
          return ContentType.socialMedia;
        case 'shopping':
          return ContentType.shopping;
        case 'news':
          return ContentType.news;
        case 'reference':
          return ContentType.reference;
        default:
          return ContentType.other;
      }
    }
    return ContentType.other;
  }
}

/// Unified page information combining tabs and bookmarks
class UnifiedPageInfo {
  final String id;
  final String url;
  final String title;
  final String? faviconUrl;
  final ContentSummary? contentSummary;
  final List<String> keywords;
  final String? category;
  final PageSourceType sourceType;
  final BrowserType? browserType;
  final DateTime createdAt;
  final DateTime lastAccessed;
  final int accessCount;
  final bool hasBookmark;
  final bool hasPendingChanges;

  UnifiedPageInfo({
    required this.id,
    required this.url,
    required this.title,
    this.faviconUrl,
    this.contentSummary,
    required this.keywords,
    this.category,
    required this.sourceType,
    this.browserType,
    required this.createdAt,
    required this.lastAccessed,
    required this.accessCount,
    this.hasBookmark = false,
    this.hasPendingChanges = false,
  });

  factory UnifiedPageInfo.fromJson(Map<String, dynamic> json) {
    return UnifiedPageInfo(
      id: json['id'] ?? '',
      url: json['url'] ?? '',
      title: json['title'] ?? '',
      faviconUrl: json['favicon_url'],
      contentSummary: json['content_summary'] != null
          ? ContentSummary.fromJson(json['content_summary'])
          : null,
      keywords: List<String>.from(json['keywords'] ?? []),
      category: json['category'],
      sourceType: _parseSourceType(json['source_type']),
      browserType: _parseBrowserType(json['browser_type']),
      createdAt: DateTime.tryParse(json['created_at'] ?? '') ?? DateTime.now(),
      lastAccessed:
          DateTime.tryParse(json['last_accessed'] ?? '') ?? DateTime.now(),
      accessCount: json['access_count'] ?? 0,
      hasBookmark: json['has_bookmark'] ?? false,
      hasPendingChanges: json['has_pending_changes'] ?? false,
    );
  }

  static PageSourceType _parseSourceType(dynamic value) {
    if (value is Map) {
      if (value.containsKey('ActiveTab')) return PageSourceType.activeTab;
      if (value.containsKey('Bookmark')) return PageSourceType.bookmark;
      if (value.containsKey('ClosedTab')) return PageSourceType.closedTab;
      if (value.containsKey('ArchivedContent'))
        return PageSourceType.archivedContent;
    }
    return PageSourceType.activeTab;
  }

  static BrowserType? _parseBrowserType(dynamic value) {
    if (value is String) {
      switch (value.toLowerCase()) {
        case 'chrome':
          return BrowserType.chrome;
        case 'firefox':
          return BrowserType.firefox;
        case 'edge':
          return BrowserType.edge;
        case 'safari':
          return BrowserType.safari;
      }
    }
    return null;
  }

  String get domain {
    try {
      final uri = Uri.parse(url);
      return uri.host;
    } catch (_) {
      return url;
    }
  }
}
