import 'page_info.dart';

/// Smart group type
enum GroupType {
  domain,
  topic,
  contentType,
  userDefined,
  aiGenerated,
}

/// Smart group for organizing pages
class SmartGroup {
  final String id;
  final String name;
  final String description;
  final GroupType groupType;
  final List<String> pageIds;
  final DateTime createdAt;
  final bool autoGenerated;
  final double similarityThreshold;
  final String? algorithm;
  final double? confidence;

  SmartGroup({
    required this.id,
    required this.name,
    required this.description,
    required this.groupType,
    required this.pageIds,
    required this.createdAt,
    required this.autoGenerated,
    required this.similarityThreshold,
    this.algorithm,
    this.confidence,
  });

  factory SmartGroup.fromJson(Map<String, dynamic> json) {
    return SmartGroup(
      id: json['id'] ?? '',
      name: json['name'] ?? '',
      description: json['description'] ?? '',
      groupType: _parseGroupType(json['group_type']),
      pageIds: List<String>.from(json['pages'] ?? []),
      createdAt: DateTime.tryParse(json['created_at'] ?? '') ?? DateTime.now(),
      autoGenerated: json['auto_generated'] ?? false,
      similarityThreshold: (json['similarity_threshold'] ?? 0.0).toDouble(),
      algorithm: json['group_type']?['AIGenerated']?['algorithm'],
      confidence: json['group_type']?['AIGenerated']?['confidence']?.toDouble(),
    );
  }

  static GroupType _parseGroupType(dynamic value) {
    if (value is Map) {
      if (value.containsKey('Domain')) return GroupType.domain;
      if (value.containsKey('Topic')) return GroupType.topic;
      if (value.containsKey('ContentType')) return GroupType.contentType;
      if (value.containsKey('AIGenerated')) return GroupType.aiGenerated;
    }
    if (value == 'UserDefined') return GroupType.userDefined;
    return GroupType.userDefined;
  }

  int get pageCount => pageIds.length;
}
